# Generated by Django 5.1.3 on 2025-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fma_app', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
