# Generated by Django 5.1.3 on 2025-02-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fma_app', '0004_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fma_app.payment'),
        ),
    ]
